- name: openvino_model_server_main
  automerge: 'yes'
  src:
    url:  https://github.com/openvinotoolkit/model_server.git
    branch: main
  dest:
    url: https://github.com/rpancham/model_server.git
    branch: main