- name: openvino_model_server
  automerge: 'no'
  src:
    url: https://github.com/opendatahub-io/openvino_model_server.git
    branch: main
  dest:
    url: https://github.com/openvinotoolkit/model_server.git
    branch: main