- name: openvino_model_server_main
  automerge: 'no'
  src:
    url: https://github.com/openvinotoolkit/model_server.git
    branch: main
  dest:
    url: https://github.com/rpancham/model_server.git
    branch: main
- name: openvino_model_server_main
  automerge: 'no'
   src:
    url: https://github.com/openvinotoolkit/model_server.git
    branch: releases/2023/3
  dest:
    url: https://github.com/rpancham/model_server.git
    branch: release