name: Syncher

on:
  push:
    branches:
      - main

jobs:
  synch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Syncher
      run: |
      